# Generated by Django 6.0.3 on 2026-04-05 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('organisation', models.CharField(max_length=200)),
                ('region', models.CharField(choices=[('darwin', 'Darwin'), ('alice_springs', 'Alice Springs'), ('katherine', 'Katherine'), ('tennant_creek', 'Tennant Creek'), ('nhulunbuy', 'Nhulunbuy'), ('other', 'Other')], max_length=50)),
                ('category', models.CharField(choices=[('diversion', 'Diversion'), ('throughcare', 'Throughcare'), ('support', 'Support'), ('mentoring', 'Mentoring'), ('justice', 'Justice'), ('education', 'Education'), ('other', 'Other')], max_length=50)),
                ('age_min', models.PositiveIntegerField()),
                ('age_max', models.PositiveIntegerField()),
                ('is_available', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('short_description', models.TextField()),
                ('website', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
