# Generated by Django 4.2.30 on 2026-04-10 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youthjustice_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrimeData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('offence_category', models.CharField(max_length=200)),
                ('offence_type', models.CharField(max_length=200)),
                ('alcohol_involvement', models.CharField(default='-', max_length=20)),
                ('dv_involvement', models.CharField(default='-', max_length=20)),
                ('region', models.CharField(max_length=100)),
                ('count', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Crime Statistic',
                'verbose_name_plural': 'Crime Statistics',
            },
        ),
        migrations.CreateModel(
            name='EngagementData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('sex', models.CharField(max_length=30)),
                ('indigenous_status', models.CharField(max_length=100)),
                ('measure', models.CharField(max_length=300)),
                ('value_nt', models.FloatField(blank=True, null=True)),
                ('value_national', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Engagement Record',
                'verbose_name_plural': 'Engagement Data',
            },
        ),
        migrations.AlterField(
            model_name='program',
            name='category',
            field=models.CharField(choices=[('diversion', 'Diversion'), ('throughcare', 'Throughcare'), ('support', 'Support'), ('mentoring', 'Mentoring'), ('justice', 'Justice'), ('education', 'Education'), ('rehabilitation', 'Rehabilitation'), ('other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='program',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
