# Generated by Django 4.2.30 on 2026-04-13 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youthjustice_app', '0003_alter_program_options_alter_crimedata_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='crimedata',
            options={'ordering': ['-year', '-month'], 'verbose_name': 'Crime Statistic', 'verbose_name_plural': 'Crime Statistics'},
        ),
        migrations.AlterModelOptions(
            name='engagementdata',
            options={'ordering': ['-year'], 'verbose_name': 'Engagement Record', 'verbose_name_plural': 'Engagement Data'},
        ),
        migrations.RemoveField(
            model_name='program',
            name='owner',
        ),
        migrations.AlterField(
            model_name='crimedata',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='engagementdata',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='program',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.DeleteModel(
            name='OrganisationProfile',
        ),
    ]
