# Generated by Django 6.0.3 on 2026-04-14 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youthjustice_app', '0004_alter_crimedata_options_alter_engagementdata_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crimedata',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='engagementdata',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='program',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
