# Generated by Django 6.0.3 on 2026-04-16 00:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youthjustice_app', '0005_alter_crimedata_id_alter_engagementdata_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('organisation_type', models.CharField(choices=[('government', 'Government'), ('nonprofit', 'Non-profit'), ('community', 'Community'), ('education', 'Education'), ('other', 'Other')], default='community', max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('website', models.URLField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Organisation',
                'verbose_name_plural': 'Organisations',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='program',
            options={'ordering': ['name'], 'verbose_name': 'Program', 'verbose_name_plural': 'Programs'},
        ),
        migrations.CreateModel(
            name='CrimeDataSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('region', models.CharField(max_length=100)),
                ('summary', models.TextField()),
                ('total_offences', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crime_snapshots', to='youthjustice_app.program')),
            ],
            options={
                'ordering': ['-year', 'program__name'],
            },
        ),
        migrations.AlterField(
            model_name='program',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='youthjustice_app.organisation'),
        ),
    ]
