# Generated by Django 6.0.3 on 2026-05-27 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youthjustice_app', '0006_organisation_alter_program_options_crimedatasnapshot_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HelpRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('new', 'New'), ('in_review', 'In Review'), ('contacted', 'Contacted'), ('closed', 'Closed')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='help_requests', to='youthjustice_app.program')),
            ],
            options={
                'verbose_name': 'Help Request',
                'verbose_name_plural': 'Help Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProgramInfoReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_type', models.CharField(choices=[('wrong_contact', 'Wrong contact information'), ('broken_link', 'Broken website link'), ('wrong_availability', 'Wrong availability status'), ('wrong_details', 'Wrong program details'), ('other', 'Other')], max_length=30)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('reviewed', 'Reviewed'), ('fixed', 'Fixed'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='info_reports', to='youthjustice_app.program')),
            ],
            options={
                'verbose_name': 'Program Info Report',
                'verbose_name_plural': 'Program Info Reports',
                'ordering': ['-created_at'],
            },
        ),
    ]
